-- ============================================
-- MCAT content category — schema + backfill
-- Generated by scripts/classify-categories.py; run in Supabase SQL editor.
-- ============================================

-- 1. Add the column (nullable: CARS + research-methods batches stay null).
alter table public.questions add column if not exists content_category text;

-- 2. Backfill by batch. All questions in a batch share one content category.
update public.questions set content_category = '10A' where batch in ('B016', 'B080', 'B111', 'B206', 'B270', 'B325');
update public.questions set content_category = '1A' where batch in ('B011', 'B065', 'B409', 'B417', 'B428', 'B439');
update public.questions set content_category = '1B' where batch in ('B008', 'B054', 'B100', 'B105', 'B116', 'B404', 'B413', 'B434', 'B436');
update public.questions set content_category = '1C' where batch in ('B015', 'B063', 'B071', 'B085', 'B109', 'B158', 'B161', 'B187', 'B193', 'B201', 'B408', 'B419', 'B429');
update public.questions set content_category = '1D' where batch in ('B003', 'B004', 'B046', 'B059', 'B061', 'B090', 'B094', 'B129', 'B144', 'B155', 'B181', 'B191', 'B205', 'B401', 'B403', 'B411', 'B420', 'B427', 'B430', 'B433', 'B440');
update public.questions set content_category = '2A' where batch in ('B030', 'B062', 'B095', 'B124', 'B163', 'B174', 'B178', 'B402', 'B405', 'B412', 'B437');
update public.questions set content_category = '2B' where batch in ('B022', 'B036', 'B104', 'B118', 'B414', 'B424');
update public.questions set content_category = '2C' where batch in ('B023', 'B031', 'B084', 'B117', 'B127', 'B410', 'B418', 'B426', 'B435');
update public.questions set content_category = '3A' where batch in ('B018', 'B055', 'B079', 'B137', 'B147', 'B196', 'B209', 'B407', 'B416', 'B422', 'B423', 'B432');
update public.questions set content_category = '3B' where batch in ('B037', 'B047', 'B053', 'B064', 'B072', 'B074', 'B075', 'B082', 'B135', 'B140', 'B149', 'B166', 'B169', 'B170', 'B184', 'B406', 'B415', 'B421', 'B425', 'B431', 'B438');
update public.questions set content_category = '4A' where batch in ('B087', 'B101', 'B162', 'B370', 'B371', 'B391');
update public.questions set content_category = '4B' where batch in ('B001', 'B051', 'B160', 'B186', 'B208', 'B333', 'B363', 'B369', 'B372', 'B382', 'B392');
update public.questions set content_category = '4C' where batch in ('B002', 'B045', 'B052', 'B077', 'B086', 'B110', 'B130', 'B134', 'B154', 'B165', 'B171', 'B192', 'B204', 'B332', 'B335', 'B362', 'B373', 'B378', 'B383', 'B389', 'B393', 'B397');
update public.questions set content_category = '4D' where batch in ('B021', 'B034', 'B076', 'B091', 'B150', 'B175', 'B183', 'B195', 'B334', 'B339', 'B364', 'B374', 'B375', 'B384', 'B385', 'B394');
update public.questions set content_category = '4E' where batch in ('B028', 'B068', 'B106', 'B139', 'B340', 'B368', 'B400');
update public.questions set content_category = '5A' where batch in ('B010', 'B026', 'B066', 'B088', 'B157', 'B168', 'B179', 'B180', 'B190', 'B331', 'B361', 'B377', 'B387', 'B396');
update public.questions set content_category = '5B' where batch in ('B029');
update public.questions set content_category = '5C' where batch in ('B035', 'B107', 'B115', 'B141', 'B338', 'B367', 'B380', 'B390', 'B399');
update public.questions set content_category = '5D' where batch in ('B033', 'B050', 'B078', 'B081', 'B112', 'B125', 'B126', 'B146');
update public.questions set content_category = '5E' where batch in ('B012', 'B017', 'B067', 'B096', 'B097', 'B099', 'B114', 'B136', 'B145', 'B200', 'B336', 'B337', 'B365', 'B366', 'B376', 'B379', 'B381', 'B386', 'B388', 'B395', 'B398');
update public.questions set content_category = '6A' where batch in ('B032', 'B069', 'B156', 'B177', 'B274', 'B286', 'B314');
update public.questions set content_category = '6B' where batch in ('B013', 'B038', 'B042', 'B056', 'B092', 'B121', 'B164', 'B194', 'B202', 'B272', 'B283', 'B284', 'B290', 'B296', 'B299', 'B303', 'B319', 'B320', 'B326');
update public.questions set content_category = '6C' where batch in ('B025', 'B098', 'B120', 'B173', 'B185', 'B273', 'B279', 'B292', 'B294', 'B308');
update public.questions set content_category = '7A' where batch in ('B027', 'B039', 'B070', 'B102', 'B108', 'B119', 'B131', 'B151', 'B167', 'B277', 'B287', 'B293', 'B300', 'B305', 'B309', 'B313', 'B317', 'B322', 'B330');
update public.questions set content_category = '7B' where batch in ('B057', 'B182', 'B276', 'B289', 'B291', 'B310');
update public.questions set content_category = '7C' where batch in ('B005', 'B089', 'B148', 'B271', 'B281', 'B302', 'B311', 'B315', 'B321', 'B323');
update public.questions set content_category = '8A' where batch in ('B020', 'B275', 'B297', 'B304', 'B324');
update public.questions set content_category = '8B' where batch in ('B009', 'B128', 'B197', 'B301', 'B316', 'B328');
update public.questions set content_category = '8C' where batch in ('B285');
update public.questions set content_category = '9A' where batch in ('B040', 'B041', 'B278', 'B282', 'B295', 'B307', 'B312', 'B327');

-- 3. Index for filter queries.
create index if not exists idx_questions_content_category on public.questions(content_category);

